### ISSUE TITLE
Уровень не завершается после сбора всех монет

### ISSUE THREAD

**Issue by HatoKrutix** [true-grue/DandyBot#2]
Игра не горантирует что на уровне есть монеты, в случае если не последний бот в списке запуска собирает последнюю монету.
Проверка наличия монет проводится только при старте хода, а не при сборе монеты, из-за чего может возникнуть ситуация когда после сбора последней монеты следующий бот пытается найти монеты, но их на карте уже нет

**Comment by true-grue** [comment]
Спасибо, Вы обнаружили интересную проблему!
Я постарался ее исправить, но, как мне кажется, получилось проще, чем в предложенном варианте. Посмотрите, пожалуйста.
P.S. И жду от Вас группу и номер варианта!
